### Update you.com API Key
POST http://localhost:3000/apiKey
Content-Type: application/json
Accept: application/json

{
    "apiKey":"POT5GI2F7DDHUQ710JY96TFCEGYWWOJ44O"
}

### POST Camel Yaml
POST http://localhost:3000/camel-dsl
Content-Type: application/json
Accept: application/json

{
    "text":"read csv file"
}